project_id: "[YOUR CUSTOM VISION PROJECT ID]"
custom_vision:
  endpoint: "[YOUR CUSTOM VISION RESOURCE ENDPOINT]" # e.g. westeurope.api.cognitive.microsoft.com
  training_key: "***"
  prediction_key: "***"
  prediction_resource_id: "[YOUR CUSTOM VISION RESOURCE ID]"
firenet_path: "[PATH]/FireNet"
firenet_tags:
  Fire_Extinguisher: FireExtinguisher
upload_batch_size: 50 # max 64
