name: azure-firenet
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - click=8.0.1
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flake8=3.9.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - jsonschema=3.2.0
  - jupyter_client=7.0.1
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - readline=8.1
  - regex=2021.8.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - testpath=0.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - pip:
    - azure-cognitiveservices-vision-customvision==3.1.0
    - azure-common==1.1.27
    - charset-normalizer==2.0.7
    - idna==3.3
    - isodate==0.6.0
    - msrest==0.6.21
    - oauthlib==3.1.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - urllib3==1.26.7
